---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu
  - name: centos
  - name: debian

suites:
  - name: default
    run_list:
      - recipe[gor::default]
